toc:
  - name: GenIRSim
    description: |
      TODO [[code](https://github.com/webis-de/scriptor)] [[package](https://www.npmjs.com/package/@webis-de/scriptor)]
  - name: Evaluators
  - Evaluator
  - ReadabilityEvaluator
  - name: Systems
  - System
  - GenerativeElasticSystem
  - name: Users
  - User
  - StaticUser
  - name: Utility
  - LLM
  - Logbook
  - templates
  - name: Types
  - EvaluationResult
  - EVALUATION_RESULT
  - LLMConfiguration
  - LogbookEntry
  - SystemResponse
  - SYSTEM_RESPONSE
  - Topic
  - UserTurn
  - USER_TURN
