toc:
  - name: GenIRSim
    description: |
      TODO [[code](https://github.com/webis-de/scriptor)] [[package](https://www.npmjs.com/package/@webis-de/scriptor)]
  - Evaluator
  - Logbook
  - System
  - User
  - name: Types
  - EvaluationResult
  - LogbookEntry
  - SystemResponse
  - Topic
  - UserTurn
  - name: Utility
  - templates
