name: Publish to NPM

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NPM setup
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: NPM publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

